# Generated by Django 3.0.2 on 2020-06-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhaSquared', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message',
            new_name='comment',
        ),
    ]
