# Generated by Django 3.0.2 on 2020-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhaSquared', '0002_auto_20200623_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
