# Generated by Django 3.0.2 on 2020-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhaSquared', '0003_email_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_list',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
